local_workspace: workspace/adampi_32p
# MPI config
mpi.num_bins_coarse: 32
mpi.use_alpha: false
training.src_rgb_blending: true
training.step_iter: 3
training.dpn_fmn_iter: 12000
training.dpn_fix_iter: [12000, 36000]
training.global_steps: 42000

# strategy
disp.dpn_input_strategy: uniform  # [uniform, randbins, random, heu-randbins, heu-uniform]

# loss config
training.rank_loss_weight: 100
training.assign_loss_weight: 10
training.imit_loss_weight: 10
training.occ_color_loss_weight: 5
training.disp_loss_weight: 1
training.occ_disp_loss_weight: 5
training.percept_loss_weight: 0.1
training.ffl_loss_weight: 10
training.ffl_alpha: 3
training.smooth_loss_weight: 0.01

# load checkpoint config
training.pretrained_checkpoint_path: null
training.load_part_list: ["dpn", "fmn"]

training.use_multi_scale: true
vis.save_dir: "vis"
mpi.disparity_end: 0.001
mpi.disparity_start: 1.0
data.img_h: 384
data.img_w: 512 
data.name: YOUR_DATASET_NAME 
data.img_pre_downsample_ratio: 7.875
data.per_gpu_batch_size: 4
data.training_set_path: YOUR_TRAINING_SET 
data.val_set_path: YOUR_VAL_SET 
lr.backbone_lr: 0.001
lr.decay_gamma: 0.1
lr.decay_steps: 5,10
lr.decoder_lr: 0.001
lr.weight_decay: 4.0e-05
model.imagenet_pretrained: false
mpi.num_bins_fine: 0
mpi.valid_mask_threshold: 2
mpi.fix_disparity: false
loss.smoothness_lambda_v1: 0.0
loss.smoothness_gmin: 2.0
loss.smoothness_grad_ratio: 0.1
loss.smoothness_lambda_v2: 0.01
training.epochs: 15
training.eval_interval: 10000 
training.gpus: 0
training.sample_interval: 30